title: GloDroid
description: Free and opensource AOSP based Android for the world's most accessible development platforms.
remote_theme: https://github.com/MaksymPrymierov/jekyll-theme-glodroid
show_downloads: true

github:
  public: true
  is_project_page: true
  zip_url: https://github.com/GloDroid/glodroid_manifest/archive/v0.1.0.zip
  tar_url: https://github.com/GloDroid/glodroid_manifest/archive/v0.1.0.tar.gz
  repository_url: https://github.com/GloDroid/glodroid_manifest
